include:
  - '/r4.2/gitlab-base.yml'
  - '/r4.2/gitlab-host-build.yml'
  - '/r4.2/gitlab-host-vm-openqa.yml'
  - '/r4.2/gitlab-vm-fedora-build.yml'
  - '/r4.2/gitlab-vm-debian-build.yml'
#  - '/r4.2/gitlab-vm-archlinux-build.yml'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

variables:
  PR_LABEL:
    value: "openqa-pending"
    description: "Collect PRs with this label for the test run"
  SELINUX_TEMPLATES:
    description: "Test SELinux on those (space separated) templates"
  UPDATE_TEMPLATES:
    description: "List of templates to update (space separated)"
  TEST_TEMPLATES:
    description: "List of templates to run tests on (space separated)"
  DEFAULT_TEMPLATE:
    description: "Template to set as default, can be abbreviated like 'debian' for latest Debian version"

r4.2:prep:sources:
  extends: .r4.2_components_prepare
  artifacts:
    expire_in: 1 day
    paths:
      - qubes-builder.tar.xz
      - pull-requests.txt
  script:
    - git config --global user.email "user@example.com"
    - git config --global user.name "builder"
    - cp ./scripts/gitlab-*v2 ~/qubes-builder/
    - "echo increment-devel-versions: true >> ~/qubes-builder/builder.yml"
    - ./scripts/get-prs-sourcesv2 "$PR_LABEL"
    - tar cJf $CI_PROJECT_DIR/qubes-builder.tar.xz --strip-components=1 -C ~/ qubes-builder

publish:openqa:
  tags:
    - docker
  needs:
    # for pull-requests.txt
    - r4.2:prep:sources
    - r4.2:publish:repo
  stage: publish
  script:
    - ./scripts/start-openqa-repo
