include:
  - '/r4.3/gitlab-base.yml'
# host build job defined explicitly below, with slight modification
#  - '/r4.3/gitlab-host-build.yml'
  - '/r4.3/gitlab-host-vm-openqa.yml'
  - '/r4.3/gitlab-vm-fedora-build.yml'
  - '/r4.3/gitlab-vm-debian-build.yml'
  - '/r4.3/gitlab-vm-archlinux-build.yml'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

variables:
  PR_LABEL:
    value: "openqa-pending"
    description: "Collect PRs with this label for the test run"
  SELINUX_TEMPLATES:
    description: "Test SELinux on those (space separated) templates"
  UPDATE_TEMPLATES:
    description: "List of templates to update (space separated)"
  TEST_TEMPLATES:
    description: "List of templates to run tests on (space separated)"
  DEFAULT_TEMPLATE:
    description: "Template to set as default, can be abbreviated like 'debian' for latest Debian version"

r4.3:prep:sources:
  extends: .r4.3_components_prepare
  artifacts:
    expire_in: 1 day
    paths:
      - qubes-builder.tar.xz
      - pull-requests.txt
  variables:
    COMPONENTS_GROUP: " vmm-xen-windows-pvdrivers core-vchan-xen windows-utils core-qubesdb core-agent-windows gui-common gui-agent-windows installer-qubes-os-windows-tools "
  script:
    - git config --global user.email "user@example.com"
    - git config --global user.name "builder"
    - cp ./scripts/gitlab-*v2 ~/qubes-builder/
    - cp ./scripts/repo-key.gpgbatch ~/qubes-builder/
    - cp ./scripts/combine-and-sign-repo ~/qubes-builder/
    - ./scripts/get-prs-sourcesv2 "$PR_LABEL" "$COMPONENTS_GROUP"
    - tar cJf $CI_PROJECT_DIR/qubes-builder.tar.xz --strip-components=1 -C ~/ qubes-builder

# custom host build jobs to include also QWT but reuse common sources
r4.3:build:vm-win10:
  extends: .r4.3_components_build
  tags:
  - qubes-windows
  needs:
  - r4.3:prep:sources
  artifacts:
    paths:
      - artifacts/repository
      - artifacts/components
      - artifacts/logs

r4.3:build:host-fc41:
  extends: .r4.3_components_build
  needs:
    - r4.3:prep:sources
    - r4.3:build:vm-win10

publish:openqa:
  tags:
    - docker
  needs:
    # for pull-requests.txt
    - r4.3:prep:sources
    - r4.3:publish:repo
  stage: publish
  script:
    - ./scripts/start-openqa-repo
