include:
 - example-configs/qubes-os-r4.2.yml

backend-vmm: xen

debug: true
verbose: true

reuse-fetched-source: true
skip-git-fetch: true
increment-devel-versions: true

repository-publish:
  components: current-testing
  templates: templates-community-testing

use-qubes-repo:
  version: 4.2
  testing: true

distributions:
  - host-fc32
  - host-fc37
  - vm-bullseye
  - vm-bookworm
  - vm-fc37
  - vm-fc38
  - vm-centos-stream8
  - vm-archlinux
  - vm-focal
  - vm-jammy

+templates:
  - fedora-38:
      dist: fc38
      options:
        - selinux
  - fedora-38-minimal:
      dist: fc38
      flavor: minimal
  - debian-12:
      dist: bookworm
      options:
        - standard
        - firmware
  - debian-12-minimal:
      dist: bookworm
      flavor: minimal
      options:
      - no-recommends
  - debian-12-xfce:
      dist: bookworm
      flavor: xfce
      options:
        - standard
        - firmware
  - centos-stream-8:
      dist: centos-stream8
  - centos-stream-9:
      dist: centos-stream9
  - centos-stream-10:
      dist: centos-stream10

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
