git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-

include:
 - example-configs/qubes-os-r4.2.yml

backend-vmm: xen

debug: true
verbose: true

reuse-fetched-source: true
skip-git-fetch: true

use-qubes-repo:
  version: 4.1
  testing: true

distributions:
  - host-fc32
  - vm-bullseye
  - vm-fc35

#executor:
#  type: local
#  options:
#    user: "gitlab-runner"
#    group: "gitlab-runner"

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
