include:
 - example-configs/qubes-os-r4.3.yml

git:
  branch: main
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'


backend-vmm: xen
verbose: true
reuse-fetched-source: true
skip-git-fetch: true
increment-devel-versions: true

repository-publish:
  components: current-testing
  templates: templates-community-testing

use-qubes-repo:
  version: 4.3
  testing: true

+components:
  - builder-archlinux:
      packages: false
      branch: main
  - ansible:
      verification-mode: insecure-skip-checking

distributions:
  - host-fc41
  - vm-win10:
     stages:
     - build:
         configuration: debug
         sign-qube: win-sign-test
         sign-key-name: "Qubes Windows Tools"
         test-sign: true
         executor:
           type: windows
           options:
             dispvm: win-builder-dvm
             user: user
             ewdk: /home/user/ewdk.iso
             threads: 2
  - vm-bookworm
  - vm-trixie
  - vm-fc41
  - vm-fc42
  - vm-fc43
  - vm-archlinux
  - vm-jammy
  - vm-noble

+templates:
  - fedora-40:
      dist: fc40
      options:
        - selinux
  - fedora-40-minimal:
      dist: fc40
      flavor: minimal
  - fedora-41:
      dist: fc41
      options:
        - selinux
  - fedora-41-xfce:
      dist: fc41
      flavor: xfce
      options:
        - selinux
  - fedora-41-minimal:
      dist: fc41
      flavor: minimal
  - fedora-42:
      dist: fc42
      options:
        - selinux
  - fedora-42-xfce:
      dist: fc42
      flavor: xfce
      options:
        - selinux
  - fedora-42-minimal:
      dist: fc42
      flavor: minimal
  - debian-12:
      dist: bookworm
      options:
        - gnome
        - firmware
  - debian-12-minimal:
      dist: bookworm
      flavor: minimal
      options:
      - no-recommends
  - debian-12-xfce:
      dist: bookworm
      flavor: xfce
      options:
        - standard
        - firmware
  - debian-13:
      dist: trixie
      options:
        - gnome
        - firmware
  - debian-13-minimal:
      dist: trixie
      flavor: minimal
      options:
      - no-recommends
  - debian-13-xfce:
      dist: trixie
      flavor: xfce
      options:
        - standard
        - firmware
  - archlinux:
      dist: archlinux

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local

mirrors:
  archlinux:
    - https://archlinux.mirrors.ovh.net/archlinux
    - https://mirrors.gandi.net/archlinux
    - https://arch.yourlabs.org
    - https://mirrors.edge.kernel.org/archlinux
