include:
 - example-configs/qubes-os-r4.2.yml

git:
  branch: main
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'


backend-vmm: xen
verbose: true
reuse-fetched-source: true
skip-git-fetch: true
increment-devel-versions: true

repository-publish:
  components: current-testing
  templates: templates-community-testing

use-qubes-repo:
  version: 4.2
  testing: true

+components:
  - builder-archlinux:
      packages: false
      branch: main

distributions:
  - host-fc32
  - host-fc37
  - vm-bullseye
  - vm-bookworm
  - vm-trixie
  - vm-fc41
  - vm-fc42
  - vm-centos-stream8
  - vm-archlinux
  - vm-focal
  - vm-jammy
  - vm-noble

+templates:
  - fedora-41:
      dist: fc41
      options:
        - selinux
  - fedora-41-minimal:
      dist: fc41
      flavor: minimal
  - debian-12:
      dist: bookworm
      options:
        - gnome
        - firmware
  - debian-12-minimal:
      dist: bookworm
      flavor: minimal
      options:
      - no-recommends
  - debian-12-xfce:
      dist: bookworm
      flavor: xfce
      options:
        - standard
        - firmware
  - debian-13:
      dist: trixie
      options:
        - gnome
        - firmware
  - debian-13-minimal:
      dist: trixie
      flavor: minimal
      options:
      - no-recommends
  - debian-13-xfce:
      dist: trixie
      flavor: xfce
      options:
        - standard
        - firmware
  - centos-stream-8:
      dist: centos-stream8
  - centos-stream-9:
      dist: centos-stream9
  - centos-stream-10:
      dist: centos-stream10
  - archlinux:
      dist: archlinux

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
