git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-

backend-vmm: xen

debug: true
verbose: true

reuse-fetched-source: true

use-qubes-repo:
  version: 4.1
  testing: true

distributions:
  - host-fc32
  - vm-bullseye
  - vm-fc35

executor:
  type: local
  options:
    user: "gitlab-runner"
    group: "gitlab-runner"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign
  - publish
  - upload
