include:
 - example-configs/qubes-os-r4.2.yml

backend-vmm: xen

debug: true
verbose: true

reuse-fetched-source: true
skip-git-fetch: true
increment-devel-versions: true

use-qubes-repo:
  version: 4.2
  testing: true

distributions:
  - host-fc32
  - host-fc37
  - vm-bullseye
  - vm-bookworm
  - vm-fc36
  - vm-fc37
  - vm-fc38
  - vm-centos-stream8
  - vm-archlinux
  - vm-focal
  - vm-jammy

#executor:
#  type: local
#  options:
#    user: "gitlab-runner"
#    group: "gitlab-runner"

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

stages:
  - fetch
  - prep
  - pre
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
